# Generated by Django 4.1.3 on 2022-11-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bass_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bass',
            options={'verbose_name_plural': 'Basses'},
        ),
    ]
