# Generated by Django 4.1.3 on 2022-11-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_bass_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.amp')),
                ('bass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bass')),
            ],
        ),
    ]
