# Generated by Django 4.1.3 on 2022-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_amp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bass',
            name='amps',
            field=models.ManyToManyField(to='main_app.amp'),
        ),
        migrations.DeleteModel(
            name='Rig',
        ),
    ]
